### ISSUE TITLE
high sniklaus amazing programming

### ISSUE THREAD

**Issue by nabilove** [sniklaus/voxel-warriors#3]
your git on voxel-warriors is amazing and working for me , just have one issue wanted to change shape of minecraft character in [minecraft-skin] but cant find it ,seems like your pulling it from the web ,anyway let me get to the point 

how do i change voxel-engine , minecraft-skin , voxel-highlight , want to change the look of game all together thanks

**Comment by sniklaus** [comment]
You would have to change `minecraft-skin` in that case: https://github.com/maxogden/minecraft-skin

**Comment by nabilove** [comment]
sorry to reply yes I know how to change that but how do I recompile the project to show the changes because I made changes and it never appeared .dont know how to command line browserify ... dont know the command ??? is it browserify voxlib.js -o VoxRect.js ...???

**Comment by sniklaus** [comment]
Yes, you will have to utilize `browserify` again after making any changes. The following should work.

```
browserify assets/editor.debug.js | uglifyjs -o assets/editor.js
browserify assets/index.debug.js | uglifyjs -o assets/index.js
```

**Comment by nabilove** [comment]
I tried to run it on aws gamelift but its not completing fleet install its giving me an error , do you think it could work on aws with node.js

**Comment by sniklaus** [comment]
I am afraid that I do not know about GameLift, but I see no reason why it shouldn't run on a regular EC2 instance.

**Comment by nabilove** [comment]
It works fine on ec2 but gamelift allows automatic scaling , but they dont have node.js preinstalled , they want me to make a .bat that installs node.js silently no user input if it works, sniklaus quick question how would i create a new room on voxel warriors like click on this button and youll join "Murder Mystery SERVER" example, basically if I have lets says 1000 active players in lobby , i just want 20 people on the Murder Mystery Room... waths your taught

**Comment by nabilove** [comment]
just a quick note aws gamelift is so poorly documented , or ... but Fortnite uses gamelift to scale to millions of players , if someone could figure out how to put a threejs /js game on gamelift ,it will be a big boost for voxeljs or threejs library but for now we have to do it manually on ec2 , meaning if all your servers are full have to manually add new servers and on the other hand on slow times manually shuts server down
